config/routes.rb
Homework3::Application.routes.draw do
  get '/' => 'home#index', as: :home
  get '/sign_in' => 'user#sign_in'
  get '/userhome' => 'user#userhome'
  get '/article/new' => 'article#new_article'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
	def new_article
		
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def userhome

	end
	def sign_in
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/article/new_article.html.erb
<h1>Create a new article</h1>

app/views/home/index.html.erb
<h1>Index</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav>
		<ul>
			<li>
				<%= link_to('Home',home_path) %>
			</li>
			<li>
				<%= link_to('UserHome',userhome_path) %>
			</li>
			<li>
				<%= link_to('Sign In',sign_in_path)%>
			</li>
			<li>
				<%= link_to('Post New Article',article_new_path) %>
			</li>
		</ul>
	</nav>

<%= yield %>

</body>
</html>

app/views/user/sign_in.html.erb
<h1>Sign in</h1>

app/views/user/userhome.html.erb
<h1>User Home</h1>